// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF0JYs3U_WhH2s8nm23SuKDw5i8msGDYg',
    appId: '1:541716925969:web:84a2d2af18ddf090fcabb0',
    messagingSenderId: '541716925969',
    projectId: 'fireauthapp-1b878',
    authDomain: 'fireauthapp-1b878.firebaseapp.com',
    storageBucket: 'fireauthapp-1b878.firebasestorage.app',
    measurementId: 'G-F5QTLDYNXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-OEF_W3fjEFnXD6fqGCT2JW1-NM7rans',
    appId: '1:541716925969:android:c15c2c95af59514cfcabb0',
    messagingSenderId: '541716925969',
    projectId: 'fireauthapp-1b878',
    storageBucket: 'fireauthapp-1b878.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAm6Y2gKttkodovgiaM3_kjIHbAFsdVME',
    appId: '1:541716925969:ios:d4e0c0f0416ea6dafcabb0',
    messagingSenderId: '541716925969',
    projectId: 'fireauthapp-1b878',
    storageBucket: 'fireauthapp-1b878.firebasestorage.app',
    iosBundleId: 'com.example.fireauthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAm6Y2gKttkodovgiaM3_kjIHbAFsdVME',
    appId: '1:541716925969:ios:d4e0c0f0416ea6dafcabb0',
    messagingSenderId: '541716925969',
    projectId: 'fireauthapp-1b878',
    storageBucket: 'fireauthapp-1b878.firebasestorage.app',
    iosBundleId: 'com.example.fireauthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF0JYs3U_WhH2s8nm23SuKDw5i8msGDYg',
    appId: '1:541716925969:web:df63a40d5a62e739fcabb0',
    messagingSenderId: '541716925969',
    projectId: 'fireauthapp-1b878',
    authDomain: 'fireauthapp-1b878.firebaseapp.com',
    storageBucket: 'fireauthapp-1b878.firebasestorage.app',
    measurementId: 'G-6E4ZMDPVD3',
  );
}
